### ISSUE TITLE
Type Dictionary Tracking Issue

### ISSUE THREAD

**Issue by firox263** [gircore/gir.core#97]
Found a really nasty bug with the type dictionary in our lookup code. If we don't instantiate an object before using it in `WrapPointerAs<T>`, it instead falls back (as intended) to the 'lowest common denominator' type. This is needed for Gdk objects, as a `GdkScreen` is actually a `GdkWin32Screen` (but of course, that's an internal type which is not exposed to bindings), so we default to `GdkScreen` instead.

The problem however, is we end up falling back to the last *registered* type, which in most cases ends up being either `Gtk.Widget` or a plain `GObject`. This always causes an Exception when used with `WrapPointerAs<T>` since you can't cast a true `GObject` type up to a `Gdk.Screen` for example.

Since this basically involves rewriting half the typedict, I've decided to do it all in one go and fix some of the other issues we had in the process. I'm currently working on this at [firox263->feature/typedict](https://github.com/firox263/gir.core/tree/feature/typedict).

**TODO:**
- [X] Rewrite lookup code to search registered *and non-registered* types.
- [X] ~Handle Unloaded Assemblies (e.g. Cairo, Pango, etc)~ Anti-Feature -> **No Longer Considered**
- [x] Find a better way of obtaining the Namespace vs the Type Name from GObject (Currently it just takes the first "word" so `GtkTextView` -> `Gtk` + `TextView`. This is problematic with things like `GtkSourceView` where it doesn't fall under the `Gtk` assembly but does under the namespace).
- [x] Do a check with TypeDescriptors to be sure the objects are derived.
- [x] More robust handling of full type names. `Assembly.GetType(string)` needs the type name in the form `Namespace.Type`, so maybe each assembly should define some kind of metadata with the namespace it implements.
- [x] Register recursively up the entire tree where possible, as this is much cheaper than doing it later.
- [x] Optimise this with a few "fast paths" to avoid doing expensive lookups. This fixes #66 
- [x] Investigate more optimisations
